import { Challenge, Badge } from './types';
import { extraHtml, extraCss, extraJs } from './lessonsData';

export const LEVEL_THRESHOLDS = [0, 500, 1200, 2500, 4500, 7000, 10000];

export const BADGES: Record<string, Badge> = {
  first_blood: {
    id: 'first_blood',
    name: 'Khởi đầu mới',
    icon: 'Trophy',
    description: 'Hoàn thành thử thách đầu tiên',
  },
  html_master: {
    id: 'html_master',
    name: 'Kiến trúc sư',
    icon: 'Layout',
    description: 'Hoàn thành chuỗi bài HTML',
  },
  css_master: {
    id: 'css_master',
    name: 'Phù thủy Màu sắc',
    icon: 'Palette',
    description: 'Hoàn thành chuỗi bài CSS',
  },
  js_ninja: {
    id: 'js_ninja',
    name: 'Ninja JS',
    icon: 'Code',
    description: 'Hoàn thành chuỗi bài JavaScript',
  },
  streak_7: {
    id: 'streak_7',
    name: 'Ngọn lửa Đam mê',
    icon: 'Flame',
    description: 'Chuỗi 7 ngày học tập liên tiếp',
  },
  streak_30: {
    id: 'streak_30',
    name: 'Tháng nỗ lực',
    icon: 'Star',
    description: 'Chuỗi 30 ngày học tập liên tiếp',
  },
  streak_100: {
    id: 'streak_100',
    name: 'Huyền thoại',
    icon: 'Crown',
    description: 'Chuỗi 100 ngày học tập liên tiếp',
  }
};

export const CHALLENGES: Challenge[] = [
  // ==============================
  // HTML LESSONS
  // ==============================
  {
    id: 'html_1',
    title: 'Bài 1: Khởi nguồn của Web - Tiêu đề',
    difficulty: 'Dễ',
    type: 'html',
    kind: 'lesson',
    description: 'Thẻ <h1> là thẻ tiêu đề to nhất. Hãy viết mã để hiển thị dòng chữ to và rõ ràng "Hello Nhạc Cụ Mới".',
    instructions: 'Viết thẻ mở <h1> và thẻ đóng </h1>. Bên trong viết dòng chữ "Hello Nhạc Cụ Mới".',
    hint: 'Ví dụ: <h1>Xin chào</h1>',
    solution: '<h1>Hello Nhạc Cụ Mới</h1>',
    solutionExplanation: 'Thẻ <h1> giúp tạo tiêu đề chính cho trang. Cần có thẻ mở và thẻ đóng.',
    defaultCode: '<!-- Viết thẻ <h1> ở đây -->\n',
    xpReward: 100,
    validationSnippet: "return document.body.innerHTML.includes('Hello Nhạc Cụ Mới') && document.querySelector('h1') !== null;",
  },
  {
    id: 'html_2',
    title: 'Bài 2: Viết kể chuyện - Đoạn văn',
    difficulty: 'Dễ',
    type: 'html',
    kind: 'lesson',
    description: 'Dùng thẻ <p> (paragraph) để viết các đoạn văn bản dài. Hãy làm nổi bật một từ bằng thẻ <b> (bold).',
    instructions: 'Tạo thẻ <p> chứa dòng chữ "Lập trình rất thú vị". Đặt chữ "thú vị" trong thẻ <b> để in đậm.',
    hint: 'Ví dụ: <p>Hôm nay trời rất <b>đẹp</b>.</p>',
    solution: '<p>Lập trình rất <b>thú vị</b></p>',
    solutionExplanation: 'Thẻ <p> dùng để tạo một đoạn văn. Thẻ <b> nằm bên trong để in đậm một phần văn bản, đây gọi là thẻ lồng nhau.',
    defaultCode: '<!-- Viết đoạn văn chứa in đậm -->\n',
    xpReward: 120,
    validationSnippet: "const p = document.querySelector('p'); const b = document.querySelector('b'); return p && b && b.textContent === 'thú vị';",
  },
  {
    id: 'html_3',
    title: 'Bài 3: Danh sách đồ dùng',
    difficulty: 'Trung bình',
    type: 'html',
    kind: 'lesson',
    description: 'Để liệt kê các mục (món ăn, đồ vật), ta dùng thẻ <ul> (danh sách có dấu chấm) và <li> (từng mục).',
    instructions: 'Tạo danh sách <ul>. Bên trong chứa 2 thẻ <li> với nội dung "Sách" và "Bút".',
    hint: '<ul>\\n  <li>Mục 1</li>\\n</ul>',
    solution: '<ul>\n  <li>Sách</li>\n  <li>Bút</li>\n</ul>',
    solutionExplanation: 'Thẻ <ul> bọc bên ngoài cả danh sách, và mỗi thẻ <li> đại diện cho một dấu chấm tròn chứa nội dung.',
    defaultCode: '<!-- Lập danh sách ở đây -->\n',
    xpReward: 150,
    validationSnippet: "const ul = document.querySelector('ul'); return ul && ul.querySelectorAll('li').length === 2 && document.body.innerHTML.includes('Sách');",
  },
  {
    id: 'html_4',
    title: 'Bài 4: Bức ảnh đầu tiên',
    difficulty: 'Trung bình',
    type: 'html',
    kind: 'lesson',
    description: 'Web sẽ đẹp hơn khi có hình ảnh. Thẻ <img> dùng để hiển thị hình nhưng nó không cần thẻ đóng!',
    instructions: 'Chèn ảnh bằng thẻ <img>, sử dụng thuộc tính src="https://picsum.photos/100" để lấy đường dẫn ảnh.',
    hint: 'Cú pháp: <img src="đường-dẫn-ảnh">',
    solution: '<img src="https://picsum.photos/100">',
    solutionExplanation: 'Thẻ <img> là một "thẻ đơn", không cần thẻ đóng. Thuộc tính `src` (source) chỉ nguồn gốc của ảnh.',
    defaultCode: '<!-- Chèn ảnh của bạn -->\n',
    xpReward: 180,
    validationSnippet: "const img = document.querySelector('img'); return img && img.getAttribute('src') === 'https://picsum.photos/100';",
  },
  {
    id: 'html_5',
    title: 'Bài 5: Cánh cổng di chuyển',
    difficulty: 'Trung bình',
    type: 'html',
    kind: 'lesson',
    description: 'Internet là sự liên kết. Thẻ <a> (Anchor) dùng để tạo đường dẫn (link) đi trang khác.',
    instructions: 'Tạo thẻ <a> với thuộc tính href="https://google.com". Nội dung ghi là "Tìm kiếm ngay".',
    hint: 'Cú pháp: <a href="link">Câu chữ hiển thị</a>',
    solution: '<a href="https://google.com">Tìm kiếm ngay</a>',
    solutionExplanation: 'Thuộc tính `href` là nơi bạn muốn đi tới. Dòng chữ giữa thẻ mở và đóng <a> là chữ hiển thị cho người xem bấm vào.',
    defaultCode: '<!-- Tạo liên kết tại đây -->\n',
    xpReward: 200,
    validationSnippet: "const a = document.querySelector('a'); return a && a.getAttribute('href') === 'https://google.com' && a.textContent.includes('Tìm kiếm ngay');",
  },
  {
    id: 'html_6',
    title: 'Bài 6: Ô nhập liệu',
    difficulty: 'Khó',
    type: 'html',
    kind: 'lesson',
    description: 'Để người dùng gõ thông tin vào (như đăng nhập), ta cần tới thẻ <input> !',
    instructions: 'Tạo thẻ <input>. Cung cấp thuộc tính type="text" và thuộc tính placeholder="Nhập tên của bạn".',
    hint: '<input type="..." placeholder="...">',
    solution: '<input type="text" placeholder="Nhập tên của bạn">',
    solutionExplanation: '`type="text"` xác định kiểu nhập là văn bản thông thường. `placeholder` giúp hiển thị chữ mờ nhắc nhở khi ô còn trống.',
    defaultCode: '<!-- Tạo ô nhập ở đây -->\n',
    xpReward: 250,
    validationSnippet: "const inp = document.querySelector('input'); return inp && inp.getAttribute('type') === 'text' && inp.getAttribute('placeholder') === 'Nhập tên của bạn';",
  },

  {
    id: 'html_7',
    title: 'Bài 7: Nút bấm quyền lực',
    difficulty: 'Dễ',
    type: 'html',
    kind: 'lesson',
    description: 'Nơi nào có hành động, nơi đó có nút bấm. Thẻ <button> giúp người dùng có chỗ để click!',
    instructions: 'Tạo một nút bấm bằng thẻ <button>. Viết chữ "Click tôi đi" vào giữa thẻ mở và đóng.',
    hint: 'Cú pháp: <button>Click tôi đi</button>',
    solution: '<button>Click tôi đi</button>',
    solutionExplanation: 'Thẻ <button> tự động kết hợp với trình duyệt để có hiệu ứng nhấn xuống. Nó thường đi kèm JavaScript để xử lý khi người dùng ấn vào.',
    defaultCode: '<!-- Tạo nút bấm -->\n',
    xpReward: 200,
    validationSnippet: "const btn = document.querySelector('button'); return btn && btn.textContent.includes('Click tôi đi');",
  },
  {
    id: 'html_8',
    title: 'Bài 8: Chiếc hộp thần kỳ (Div)',
    difficulty: 'Trung bình',
    type: 'html',
    kind: 'lesson',
    description: 'Bạn muốn nhóm các thẻ lại với nhau để di chuyển cùng lúc? Thẻ <div> (Division) phân chia trang web thành các khu vực.',
    instructions: 'Tạo một thẻ <div>. Bên trong chứa thẻ <h1> "Tiêu đề" và thẻ <p> "Nội dung".',
    hint: '<div>\n  <h1>Tiêu đề</h1>\n  <p>Nội dung</p>\n</div>',
    solution: '<div>\n  <h1>Tiêu đề</h1>\n  <p>Nội dung</p>\n</div>',
    solutionExplanation: 'Thẻ <div> bản thân nó không làm thay đổi hiển thị, nhưng nó giống cái bao tải gom mọi thứ vào để sau này CSS sắp xếp dễ hơn.',
    defaultCode: '<!-- Tạo thẻ div chứa các thẻ con -->\n',
    xpReward: 220,
    validationSnippet: "const div = document.querySelector('div'); return div !== null && div.querySelector('h1') !== null && div.querySelector('p') !== null;",
  },
  {
    id: 'html_9',
    title: 'Bài 9: Bảng biểu siêu tốc',
    difficulty: 'Khó',
    type: 'html',
    kind: 'lesson',
    description: 'Thẻ <table> dùng để kẻ bảng dữ liệu với các Hàng (<tr>) và Ô (<td>).',
    instructions: 'Tạo thẻ <table>. Bên trong tạo 1 hàng <tr>. Bên trong hàng xuất hiện 2 ô <td> ghi "Môn", "Toán".',
    hint: '<table>\n  <tr>\n    <td>Môn</td>\n    <td>Toán</td>\n  </tr>\n</table>',
    solution: '<table>\n  <tr>\n    <td>Môn</td>\n    <td>Toán</td>\n  </tr>\n</table>',
    solutionExplanation: 'Table(bảng) > Tr (table row/hàng ngang) > Td (table data/ô dữ liệu nằm trong hàng).',
    defaultCode: '<!-- Tạo bảng dữ liệu -->\n',
    xpReward: 280,
    validationSnippet: "const t = document.querySelector('table'); return t && t.querySelector('tr') && t.querySelectorAll('td').length >= 2;",
  },
  {
    id: 'html_10',
    title: 'Bài 10: Nhóm thông tin (Form)',
    difficulty: 'Khó',
    type: 'html',
    kind: 'lesson',
    description: 'Đăng nhập hay Gửi thư đều cần một "Đơn" (Form) để nộp lên Server.',
    instructions: 'Tạo thẻ <form>. Lồng thẻ <input type="text"> và <button> "Gửi" vào đó.',
    hint: '<form>\n  <input type="text">\n  <button>Gửi</button>\n</form>',
    solution: '<form>\n  <input type="text">\n  <button>Gửi</button>\n</form>',
    solutionExplanation: 'Mọi <input> bên trong <form> sẽ gói thành một bộ dữ liệu, và <button> mặc định sẽ nộp dữ liệu biểu mẫu.',
    defaultCode: '<!-- Tạo biểu mẫu form -->\n',
    xpReward: 350,
    validationSnippet: "const f = document.querySelector('form'); return f !== null && f.querySelector('input') !== null && f.querySelector('button') !== null;",
  },
  ...extraHtml,

  // ==============================
  // CSS LESSONS
  // ==============================
  {
    id: 'css_1',
    title: 'Bài 1: Phù thủy sắc màu',
    difficulty: 'Dễ',
    type: 'css',
    kind: 'lesson',
    description: 'CSS là bộ áo ngoài của trang web. Thay vì màu chữ đen nhàm chán, ta hãy tô màu theo ý thích!',
    instructions: 'Trong thẻ <style>, đổi màu chữ (color) của thẻ h1 thành màu xanh biển (blue).',
    hint: 'Cú pháp CSS: thẻ { thuộc-tính: giá-trị; } -> h1 { color: blue; }',
    solution: '<style>\n  h1 {\n    color: blue;\n  }\n</style>\n<h1>Thế giới sắc màu</h1>',
    solutionExplanation: 'Trong CSS, ta gọi \'thẻ\' là bộ chọn (selector). Thuộc tính `color` chỉnh màu chữ.',
    defaultCode: '<h1>Thế giới sắc màu</h1>\n<style>\n  h1 {\n    \n  }\n</style>',
    xpReward: 120,
    validationSnippet: "const h1 = document.querySelector('h1'); return h1 && window.getComputedStyle(h1).color === 'rgb(0, 0, 255)';",
  },
  {
    id: 'css_2',
    title: 'Bài 2: Trang trí Phông nền',
    difficulty: 'Dễ',
    type: 'css',
    kind: 'lesson',
    description: 'Thẻ `body` nghĩa là toàn bộ trang. Chỉnh nền của body là chỉnh nền của cửa sổ web.',
    instructions: 'Bên trong <style>, đổi màu nền (background-color) của body thành màu vàng (yellow).',
    hint: 'Gõ: body { background-color: yellow; }',
    solution: '<style>\n  body {\n    background-color: yellow;\n  }\n</style>\n<h2>Nền trang lấp lánh</h2>',
    solutionExplanation: '`background-color` là thuộc tính tô nền cho một phần tử, bao gồm cả thân trang.',
    defaultCode: '<h2>Nền trang lấp lánh</h2>\n<style>\n  body {\n    \n  }\n</style>',
    xpReward: 150,
    validationSnippet: "return window.getComputedStyle(document.body).backgroundColor === 'rgb(255, 255, 0)' || window.getComputedStyle(document.body).backgroundColor === 'yellow';",
  },
  {
    id: 'css_3',
    title: 'Bài 3: Trọng lượng chữ cái',
    difficulty: 'Trung bình',
    type: 'css',
    kind: 'lesson',
    description: 'Sử dụng class (lớp) trong CSS để chỉ áp dụng kiểu cho một vài phần tử được đánh dấu sắn, thay vì tất cả!',
    instructions: 'Tạo CSS cho lớp .highlight bằng cách gắn font-size: 30px và làm đậm chữ font-weight: bold.',
    hint: 'Lớp CSS bắt đầu bằng dấu chấm: .highlight { font-size: 30px; font-weight: bold; }',
    solution: '<style>\n  .highlight {\n    font-size: 30px;\n    font-weight: bold;\n  }\n</style>\n<p>Lớp học <span class="highlight">Tuyệt vời</span></p>',
    solutionExplanation: 'CSS gọi các lớp bằng dấu `.` (chấm). Từ giờ, bắt kì thẻ nào có class="highlight" sẽ tự động phóng to, đậm màu!',
    defaultCode: '<p>Lớp học <span class="highlight">Tuyệt vời</span></p>\n<style>\n  .highlight {\n    \n  }\n</style>',
    xpReward: 180,
    validationSnippet: "const sp = document.querySelector('.highlight'); return sp && window.getComputedStyle(sp).fontSize === '30px' && (window.getComputedStyle(sp).fontWeight === '700' || window.getComputedStyle(sp).fontWeight === 'bold');",
  },
  {
    id: 'css_4',
    title: 'Bài 4: Khung hộp cong mềm mại',
    difficulty: 'Trung bình',
    type: 'css',
    kind: 'lesson',
    description: 'Thiết kế đẹp hiếm khi xài các hộp vuông vức sắc cạnh. Xin giới thiệu border-radius!',
    instructions: 'Tạo CSS cho .box, gán border: 2px solid black; (viền đen 2px) và border-radius: 10px; (bo tròn góc).',
    hint: '.box { border: 2px solid black; border-radius: 10px; }',
    solution: '<style>\n  .box {\n    width: 50px; height: 50px;\n    border: 2px solid black;\n    border-radius: 10px;\n  }\n</style>\n<div class="box"></div>',
    solutionExplanation: '`border` vẽ khung. `border-radius` sẽ làm cong các cạnh góc làm chi tiết trông thanh thoát hơn.',
    defaultCode: '<div class="box"></div>\n<style>\n  .box {\n    width: 50px; height: 50px;\n    \n  }\n</style>',
    xpReward: 200,
    validationSnippet: "const box = document.querySelector('.box'); return box && (window.getComputedStyle(box).borderTopWidth === '2px' || window.getComputedStyle(box).borderWidth.includes('2px')) && (window.getComputedStyle(box).borderRadius === '10px' || window.getComputedStyle(box).borderTopLeftRadius === '10px');",
  },
  {
    id: 'css_5',
    title: 'Bài 5: Padding vs Margin',
    difficulty: 'Khó',
    type: 'css',
    kind: 'lesson',
    description: 'Khoảng cách là yếu tố quan trọng số 1 trong thiêt kế. Padding là khoảng cách TRONG, Margin là NGoÀI.',
    instructions: 'Chỉnh cho button chứa padding: 10px; (Rộng ra từ trong) và margin: 20px; (Cách xa các thứ khác bên ngoài).',
    hint: 'button { padding: 10px; margin: 20px; }',
    solution: '<style>\n  button {\n    padding: 10px;\n    margin: 20px;\n    background: pink;\n  }\n</style>\n<button>Nut Bấm</button>',
    solutionExplanation: 'Tưởng tượng Padding là độ dày mỡ của bạn, còn Margin là khoảng cách cơ thể bạn đối với người đối diện.',
    defaultCode: '<button>Nut Bấm</button>\n<style>\n  button {\n    background: pink;\n    \n  }\n</style>',
    xpReward: 250,
    validationSnippet: "const btn = document.querySelector('button'); return btn && window.getComputedStyle(btn).padding === '10px' && window.getComputedStyle(btn).margin === '20px';",
  },
  {
    id: 'css_6',
    title: 'Bài 6: Sắp xếp theo ý muốn (Flexbox)',
    difficulty: 'Khó',
    type: 'css',
    kind: 'lesson',
    description: 'Căn giữa các phần tử là nỗi ám ảnh 1 thời. Flexbox đã xuất hiện để cứu rỗi các thuật toán cực khổ đó.',
    instructions: 'Cho .container có display: flex;, và để căn giữa mọi thứ ta dùng justify-content: center; và align-items: center;',
    hint: '.container { display: flex; justify-content: center; align-items: center; }',
    solution: '<style>\n  .container {\n    height: 100px; background: #eee;\n    display: flex;\n    justify-content: center;\n    align-items: center;\n  }\n</style>\n<div class="container"><div>Giữa trung tâm</div></div>',
    solutionExplanation: 'Dùng thẻ cha bọc lấy thẻ con và thêm flexbox. Tính năng này giống chia bánh, bạn tự tìm vị trí mà không cần công thức căn lề tự đếm.',
    defaultCode: '<div class="container"><div>Giữa trung tâm</div></div>\n<style>\n  .container {\n    height: 100px;\n    background: #e2e8f0;\n    \n  }\n</style>',
    xpReward: 300,
    validationSnippet: "const box = document.querySelector('.container'); return box && window.getComputedStyle(box).display === 'flex' && window.getComputedStyle(box).justifyContent === 'center';",
  },

  {
    id: 'css_7',
    title: 'Bài 7: Phông chữ độc bản',
    difficulty: 'Trung bình',
    type: 'css',
    kind: 'lesson',
    description: 'Mặc định chữ web nhìn hơi xấu. Bạn có thể đổi sang phông khác, ví dụ Arial, Tahoma hay Roboto.',
    instructions: 'Tạo định dạng thẻ body: gán `font-family: Arial, sans-serif;` và `font-size: 20px;`.',
    hint: 'body { font-family: Arial, sans-serif; font-size: 20px; }',
    solution: '<style>\n  body {\n    font-family: Arial, sans-serif;\n    font-size: 20px;\n  }\n</style>\n<p>Chữ sẽ đổi phông hiện đại!</p>',
    solutionExplanation: 'font-family ưu tiên lấy phông chữ Arial máy tính. Font-size quyết định chữ to bao nhiêu điểm ảnh.',
    defaultCode: '<p>Chữ sẽ đổi phông hiện đại!</p>\n<style>\n  body {\n    \n  }\n</style>',
    xpReward: 180,
    validationSnippet: "return window.getComputedStyle(document.body).fontFamily.includes('Arial') && window.getComputedStyle(document.body).fontSize === '20px';",
  },
  {
    id: 'css_8',
    title: 'Bài 8: Trò chơi Trốn Tim',
    difficulty: 'Dễ',
    type: 'css',
    kind: 'lesson',
    description: 'Có những lúc ta muốn che giấu thứ gì đó đi bằng thuộc tính display!',
    instructions: 'Chỉnh cho lớp `.secret` bằng `display: none;` để giấu khối đi.',
    hint: '.secret { display: none; }',
    solution: '<style>\n  .secret {\n    display: none;\n  }\n</style>\n<div class="secret">Bạn không thấy tôi đâu</div>\n<div>Trang chính đây này</div>',
    solutionExplanation: '`display: none;` xóa hoàn toàn phần tử khỏi màn hình giống như nó chưa bao giờ tồn tại. Cực hay khi làm tính năng Ẩn/Hiện popup.',
    defaultCode: '<div class="secret">Bạn không thấy tôi đâu</div>\n<div>Trang chính đây này</div>\n<style>\n  .secret {\n    \n  }\n</style>',
    xpReward: 160,
    validationSnippet: "const div = document.querySelector('.secret'); return div && window.getComputedStyle(div).display === 'none';",
  },
  {
    id: 'css_9',
    title: 'Bài 9: Sáng tạo chiều sâu',
    difficulty: 'Khó',
    type: 'css',
    kind: 'lesson',
    description: 'Trang web là mặt phẳng 2D. Box-shadow dùng tô vùng tối ngay dưới mép hộp cho não cảm giác đây là vật thể nổi 3D (Đổ bóng).',
    instructions: 'Đổ bóng cho `.card` với mã `box-shadow: 4px 4px 10px gray;`.',
    hint: '.card { box-shadow: 4px 4px 10px gray; }',
    solution: '<style>\n  .card {\n    width: 200px; height: 100px;\n    background: white;\n    box-shadow: 4px 4px 10px gray;\n  }\n</style>\n<div class="card">Mặt thẻ xịn</div>',
    solutionExplanation: 'Lần lượt là dịch-phải (4px), dịch-xuống (4px), độ nhoè nhạt ra (10px), sau cùng là màu sắc cái bóng.',
    defaultCode: '<div class="card">Mặt thẻ nổi bật</div>\n<style>\n  .card {\n    width: 200px; height: 100px; background: white;\n    \n  }\n</style>',
    xpReward: 320,
    validationSnippet: "const el = document.querySelector('.card'); return el && window.getComputedStyle(el).boxShadow !== 'none';",
  },
  {
    id: 'css_10',
    title: 'Bài 10: Chuyển động mượt mà',
    difficulty: 'Khó',
    type: 'css',
    kind: 'lesson',
    description: 'Thuộc tính `transition` là thần chú chuyển sốc sang mượt khi 1 nút bấm bị chạm vào (hover).',
    instructions: 'Cho nút `.btn` CSS `transition: background 0.3s;` để nó đổi màu chậm rãi khi rê chuột.',
    hint: '.btn { transition: background 0.3s; }',
    solution: '<style>\n  .btn {\n    background: red;\n    transition: background 0.3s;\n  }\n  .btn:hover {\n    background: blue;\n  }\n</style>\n<button class="btn">Chạm vào đây!</button>',
    solutionExplanation: 'Dặn máy tính hễ ai thay đổi nền (background), phải làm nó chậm trong 0.3s cho mướt mắt.',
    defaultCode: '<button class="btn">Chạm vào đây!</button>\n<style>\n  .btn {\n    background: red;\n    /* Viết transition ở dưới */\n    \n  }\n  .btn:hover {\n    background: blue;\n  }\n</style>',
    xpReward: 350,
    validationSnippet: "const el = document.querySelector('.btn'); return el && window.getComputedStyle(el).transitionDuration.includes('0.3s');",
  },
  ...extraCss,

  // ==============================
  // JAVASCRIPT LESSONS
  // ==============================
  {
    id: 'js_1',
    title: 'Bài 1: Đầu bếp JavaScript',
    difficulty: 'Dễ',
    type: 'js',
    kind: 'lesson',
    description: 'JavaScript là não bộ. Các câu lệnh giúp web phản hồi như 1 cái báo động! Hãy thử hiện hộp thoại báo động.',
    instructions: 'Trong thẻ <script>, viết mã lệnh alert("Chào bạn!"); để hiện bảng nhắc nhở.',
    hint: 'Viết: alert("Chào bạn!");',
    solution: '<script>\n  alert("Chào bạn!");\n</script>',
    solutionExplanation: 'Lệnh `alert` là hàm gọi cửa sổ hiển thị một tin nhắn trên trình duyệt. Rất hữu ích khi ta muốn chọc ghẹo bạn.',
    defaultCode: '<script>\n  // Viết mã ở đây\n</script>',
    xpReward: 150,
    validationSnippet: "return document.querySelector('script') !== null && document.querySelector('script').textContent.includes('alert');",
  },
  {
    id: 'js_2',
    title: 'Bài 2: Hộp đựng trí nhớ',
    difficulty: 'Dễ',
    type: 'js',
    kind: 'lesson',
    description: 'Máy tính có não, đó là do nó biết ghi nhớ thông tin bằng các Biến (Variables).',
    instructions: 'Tạo biến số `let diemSo = 10;`. Bạn có thể in nó ra mục nhật ký console bằng lệnh `console.log(diemSo);`',
    hint: 'let diemSo = 10; console.log(diemSo);',
    solution: '<script>\n  let diemSo = 10;\n  console.log(diemSo);\n</script>',
    solutionExplanation: '`let` là từ khóa dùng tạo một hộp thông tin, hộp tên `diemSo`, và đang chứa thẻ số `10`. `console.log` in ra ẩn phía sau màn cho coder tự theo dõi.',
    defaultCode: '<script>\n  \n</script>',
    xpReward: 160,
    validationSnippet: "const code = document.querySelector('script')?.textContent || ''; return code.includes('let diemSo') && code.includes('10');",
  },
  {
    id: 'js_3',
    title: 'Bài 3: Nhà toán học đại tài',
    difficulty: 'Trung bình',
    type: 'js',
    kind: 'lesson',
    description: 'Ngôn ngữ lập trình là cái máy xoay số liệu. Dùng toán tử (+, -, *, /) để tính toán.',
    instructions: 'Gắn biến `let tong = 5 + 5;` sau đó có thể in giá trị nó ra `console.log(tong);`',
    hint: 'Nhập: let tong = 5 + 5; console.log(tong);',
    solution: '<script>\n  let tong = 5 + 5;\n  console.log(tong);\n</script>',
    solutionExplanation: 'JS sẽ thi hành phép cộng tính trước, kết quả (10) được ghi nhớ vĩnh viễn trong hộp biến `tong`.',
    defaultCode: '<script>\n  \n</script>',
    xpReward: 200,
    validationSnippet: "const code = document.querySelector('script')?.textContent || ''; return code.includes('let tong') && code.includes('5 + 5');",
  },
  {
    id: 'js_4',
    title: 'Bài 4: Ra quyết định (If / Else)',
    difficulty: 'Trung bình',
    type: 'js',
    kind: 'lesson',
    description: 'Tại sao AI khôn? AI cũng chỉ là cả chục triệu lệnh `Nếu ... Thì` ráp lại !',
    instructions: 'Viết lệnh if. Nếu 10 > 5 thì in console.log("Lớn hơn thật");',
    hint: 'if (10 > 5) { console.log("Lớn hơn thật"); }',
    solution: '<script>\n  if (10 > 5) {\n    console.log("Lớn hơn thật");\n  }\n</script>',
    solutionExplanation: 'Dữ kiện ở `if (câu-hỏi)` trả lời là Đúng, thì code trong cặp ngoặc nhọn `{}` sẽ được thi hành. Nếu Sai nó bỏ qua.',
    defaultCode: '<script>\n  \n</script>',
    xpReward: 250,
    validationSnippet: "const code = document.querySelector('script')?.textContent || ''; return code.includes('if') && code.includes('10 > 5');",
  },
  {
    id: 'js_5',
    title: 'Bài 5: Bàn tay ma thuật đổi màu',
    difficulty: 'Khó',
    type: 'js',
    kind: 'lesson',
    description: 'JavaScript mạnh mẽ bởi khả năng bẻ cong các quy tắc HTML/CSS đang mở. Nó tương tác với MÔ HÌNH DỮ LIỆU hiển thị (DOM).',
    instructions: 'Dùng `document.getElementById("tieu-de").style.color = "red";` để làm chữ đo thành đỏ 1 cách chủ động qua code JS, không dùng CSS.',
    hint: 'Nhập dòng document.getElementById("tieu-de").style.color = "red";',
    solution: '<h1 id="tieu-de">Dòng chữ chanh xả</h1>\n<script>\n  document.getElementById("tieu-de").style.color = "red";\n</script>',
    solutionExplanation: 'DOM (Tài Điệu Ôb-Dẹc) là HTML được hiểu dạng Cây. JS truy tìm theo đường dẫn tên `tieu-de` móc rễ vô đó bẻ lại màu `style.color`.',
    defaultCode: '<h1 id="tieu-de">Dòng chữ chanh xả</h1>\n<script>\n  \n</script>',
    xpReward: 300,
    validationSnippet: "const h1 = document.getElementById('tieu-de'); return h1 && h1.style.color === 'red';",
  },
  {
    id: 'js_6',
    title: 'Bài 6: Vòng tròn thời gian (Lặp For)',
    difficulty: 'Khó',
    type: 'js',
    kind: 'lesson',
    description: 'Chẳng có lập trình viên nào copy 1 đoạn 100 lần. Mã lặp `for` sẽ xé toạc định kiến lười nhác.',
    instructions: 'Tạo vòng lặp `for(let i=0; i<3; i++)` in ra `console.log(i);`',
    hint: 'for(let i=0; i<3; i++) { console.log(i); }',
    solution: '<script>\n  for(let i=0; i<3; i++) {\n    console.log(i);\n  }\n</script>',
    solutionExplanation: 'Vòng lặp có 3 thông số: Nhịp đếm bắt đầu(i=0), Điểm dừng(i<3), Bước tăng dần đếm tới khi dừng(i++). Dễ lắm',
    defaultCode: '<script>\n  \n</script>',
    xpReward: 400,
    validationSnippet: "const code = document.querySelector('script')?.textContent || ''; return code.includes('for') && code.includes('i++') && code.includes('console.log');",
  },
  {
    id: 'js_7',
    title: 'Bài 7: Phép thuật đóng gói (Hàm)',
    difficulty: 'Khó',
    type: 'js',
    kind: 'lesson',
    description: 'Một đoạn code lặp dùng đi dùng lại được bọc thành khối gọi là Hàm (Function). Cần dùng cứ gọi nó ra!',
    instructions: 'Tạo hàm: `function chao() { alert("Hi !"); }`. Sau đó gọi hàm này qua `chao();`',
    hint: 'function chao() { alert("Hi !"); } \n chao();',
    solution: '<script>\n  function chao() {\n    alert("Hi !");\n  }\n  chao();\n</script>',
    solutionExplanation: 'Function (hàm) làm nhiệm vụ chia chương trình lớn thành các chức năng nhỏ, dễ gọi khi cần.',
    defaultCode: '<script>\n  \n</script>',
    xpReward: 350,
    validationSnippet: "const code = document.querySelector('script')?.textContent || ''; return code.includes('function') && code.includes('chao()');",
  },
  {
    id: 'js_8',
    title: 'Bài 8: Chiếc tủ nhiều ngăn (Mảng Array)',
    difficulty: 'Khó',
    type: 'js',
    kind: 'lesson',
    description: 'Khi bạn có 100 món đồ nghề, thật ngớ ngẩn nếu tạo 100 cái biến. Tủ chứa danh sách gọi là Mảng (Array).',
    instructions: 'Tạo biến mảng `let doNghe = ["Kéo", "Búa", "Bao"];`',
    hint: 'let doNghe = ["Kéo", "Búa", "Bao"];',
    solution: '<script>\n  let doNghe = ["Kéo", "Búa", "Bao"];\n  console.log(doNghe[0]); // lấy Kéo ra\n</script>',
    solutionExplanation: 'Mảng (Array) gom thông tin cùng loại kề nhau trong cái ngoặc vuông `[]`. Điểm đặc biệt là số thứ tự kho lưu luôn bắt đầu bằng Số 0 !',
    defaultCode: '<script>\n  \n</script>',
    xpReward: 420,
    validationSnippet: "const code = document.querySelector('script')?.textContent || ''; return code.includes('let') && code.includes('[');",
  },
  {
    id: 'js_9',
    title: 'Bài 9: Gắn tai nghe (Sự kiện)',
    difficulty: 'Khó',
    type: 'js',
    kind: 'lesson',
    description: 'Để bỏ onclick trên HTML cũ kĩ, ta nên tách riêng logic bằng JS. addEventListener là cách dân xịn dùng.',
    instructions: 'Dùng lệnh `document.getElementById("btn").addEventListener("click", function() { alert("Đã ấn !") });`',
    hint: 'Lấy ID rồi chấm addEventListener',
    solution: '<button id="btn">Click !</button>\n<script>\n  document.getElementById("btn").addEventListener("click", function() {\n    alert("Đã ấn !");\n  });\n</script>',
    solutionExplanation: 'Hàm lắng nghe xịn hơn! Coder có thể gán 10 hành động cho nút bấm ở thẻ file JS riêng rẽ khỏi file HTML rối tung mù.',
    defaultCode: '<button id="btn">Click !</button>\n<script>\n  \n</script>',
    xpReward: 500,
    validationSnippet: "const code = document.querySelector('script')?.textContent || ''; return code.includes('addEventListener') && code.includes('click');",
  },
  {
    id: 'js_10',
    title: 'Bài 10: Máy du hành thời gian',
    difficulty: 'Khó',
    type: 'js',
    kind: 'lesson',
    description: 'Chờ xíu rồi làm. Việc trì hoãn một hàm có thể dùng qua tính năng Timeout.',
    instructions: 'Dùng lệnh `setTimeout(function() { alert("Dậy đi !"); }, 2000);` để hiện cảnh báo sau 2000 mili-giây (2 giây)',
    hint: 'setTimeout(function() { ... }, thời_gian);',
    solution: '<script>\n  setTimeout(function() {\n    alert("Dậy đi !");\n  }, 2000);\n</script>',
    solutionExplanation: 'setTimeout thực thi khối code một lần duy nhất theo sau một lượng thời gian đã xác định trước do bạn cài đặt.',
    defaultCode: '<script>\n  \n</script>',
    xpReward: 600,
    validationSnippet: "const code = document.querySelector('script')?.textContent || ''; return code.includes('setTimeout') && code.includes('2000');",
  },
  ...extraJs
];

export const getNextChallenge = (completedIds: string[], kind: 'lesson' | 'challenge' = 'lesson') => {
  return CHALLENGES.find(c => c.kind === kind && !completedIds.includes(c.id));
};
